
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.String.valueOf;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chaz
 */
public class simuleteniusEqn extends javax.swing.JFrame {

    private Object b;
    private Object c;
    private Object d;

    /**
     * Creates new form simuleteniusEqn
     */
    public simuleteniusEqn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        y_result = new javax.swing.JTextField();
        y2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        D = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        solve = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        y_ans = new javax.swing.JLabel();
        x_ans = new javax.swing.JLabel();
        F = new javax.swing.JTextField();
        x_result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Given the simuletenius equestion");
        jLabel1.setMaximumSize(new java.awt.Dimension(170, 24));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(115, 29, 380, 37);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("ax + by = c ..........(i)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 70, 210, 40);

        B.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(B);
        B.setBounds(230, 160, 50, 30);

        C.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(C);
        C.setBounds(410, 160, 50, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("dx +ey = f...........(ii)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 110, 177, 26);

        y1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y1.setText("y      +   =");
        getContentPane().add(y1);
        y1.setBounds(300, 160, 80, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("x     +");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 160, 50, 30);

        A.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(A);
        A.setBounds(110, 160, 50, 30);

        E.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(E);
        E.setBounds(230, 210, 50, 30);

        y_result.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(y_result);
        y_result.setBounds(510, 310, 50, 40);

        y2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        y2.setText("y    +    =");
        getContentPane().add(y2);
        y2.setBounds(310, 210, 80, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("x       +");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(167, 210, 54, 30);

        D.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(D);
        D.setBounds(110, 210, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("calculator");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 0, 120, 30);

        solve.setBackground(new java.awt.Color(51, 255, 153));
        solve.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        solve.setForeground(new java.awt.Color(51, 102, 0));
        solve.setText("solve");
        solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveActionPerformed(evt);
            }
        });
        getContentPane().add(solve);
        solve.setBounds(320, 270, 80, 50);

        clear.setBackground(new java.awt.Color(255, 51, 51));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("c");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(330, 360, 60, 30);

        y_ans.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        y_ans.setText("y=");
        getContentPane().add(y_ans);
        y_ans.setBounds(450, 310, 50, 30);

        x_ans.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        x_ans.setText("x =");
        getContentPane().add(x_ans);
        x_ans.setBounds(450, 260, 50, 30);

        F.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(F);
        F.setBounds(410, 210, 50, 30);

        x_result.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        getContentPane().add(x_result);
        x_result.setBounds(510, 255, 50, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   // JButton btnSolve =new JButton("solve"); //i add this button but still yet
    private void solveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveActionPerformed
        // TODO add your handling code here:
        //why an erros
     //   btnSolve.addActionListener(new ActionListener() {//added and generate object down hr
          //  @Override
          //  public void actionPerformed(ActionEvent e) {
          //      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           // }
       // });
        
        double a1 = Integer.parseInt(A.getText());
         double b1 = Integer.parseInt(B.getText());
          double c1 = Integer.parseInt(C.getText());
           double d1 = Integer.parseInt(D.getText());//why this!
            double e1 = Integer.parseInt(E.getText());
             double f1 = Integer.parseInt(F.getText());
             
             
             
             //fomulae of detaminant to calculate eqn
             double x1 = ((b1*f1)-(c1-c1*e1))/((b1*d1)-(a1*e1));
             double y1 = (c1-(a1*x1))/b1;
             
             //set x,y_ans
             x_result.setText(String.valueOf(x1));
             y_result.setText(String.valueOf(y1));
             
  
    }//GEN-LAST:event_solveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        //clear button
        A.setText(null);
        B.setText(null);
        C.setText(null);
        D.setText(null);
        E.setText(null);
        F.setText(null);
         x_result.setText(null);
         y_result.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simuleteniusEqn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simuleteniusEqn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simuleteniusEqn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simuleteniusEqn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simuleteniusEqn().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JTextField F;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton solve;
    private javax.swing.JLabel x_ans;
    private javax.swing.JTextField x_result;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    private javax.swing.JLabel y_ans;
    private javax.swing.JTextField y_result;
    // End of variables declaration//GEN-END:variables

   

    
   
}
